country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-59, 262, 59, 358],
                "x": 0,
                "y": 361,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [930, 365, 1064, 463],
                "x": 1000,
                "y": 464,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-69, 64, 69, 152],
                "x": 0,
                "y": 158,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [572, -90, 688, 9],
                "x": 624,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [646, 693, 757, 797],
                "x": 702,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-50, 236, 58, 328],
                "x": 0,
                "y": 336,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-65, 91, 64, 201],
                "x": 0,
                "y": 199,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [941, 45, 1060, 146],
                "x": 1000,
                "y": 150,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [938, 519, 1056, 602],
                "x": 1000,
                "y": 610,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [944, 173, 1068, 275],
                "x": 1000,
                "y": 268,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-51, 297, 71, 381],
                "x": 15,
                "y": 389,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [924, 371, 1033, 465],
                "x": 976,
                "y": 466,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-35, 75, 83, 173],
                "x": 24,
                "y": 172,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [581, -77, 693, 22],
                "x": 631,
                "y": 19,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [615, 583, 742, 689],
                "x": 676,
                "y": 680,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-37, 258, 87, 356],
                "x": 20,
                "y": 353,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-41, 190, 90, 276],
                "x": 28,
                "y": 284,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [917, 99, 1032, 186],
                "x": 979,
                "y": 195,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [917, 444, 1030, 550],
                "x": 967,
                "y": 553,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [918, 190, 1029, 304],
                "x": 971,
                "y": 299,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-37, 317, 84, 423],
                "x": 30,
                "y": 415,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [888, 374, 1020, 458],
                "x": 953,
                "y": 468,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-11, 82, 105, 188],
                "x": 49,
                "y": 187,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [580, -56, 706, 31],
                "x": 639,
                "y": 39,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [599, 475, 708, 591],
                "x": 651,
                "y": 582,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-24, 274, 107, 364],
                "x": 40,
                "y": 367,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [6, 251, 110, 359],
                "x": 57,
                "y": 357,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [902, 130, 1010, 239],
                "x": 959,
                "y": 234,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [879, 401, 1005, 495],
                "x": 935,
                "y": 498,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [882, 231, 997, 325],
                "x": 942,
                "y": 328,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-5, 345, 102, 442],
                "x": 45,
                "y": 439,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [874, 366, 997, 470],
                "x": 930,
                "y": 470,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [11, 98, 128, 214],
                "x": 74,
                "y": 204,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [594, -47, 712, 53],
                "x": 647,
                "y": 60,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [569, 413, 683, 513],
                "x": 626,
                "y": 506,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-7, 287, 120, 382],
                "x": 61,
                "y": 379,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [29, 318, 137, 417],
                "x": 85,
                "y": 418,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [876, 167, 993, 265],
                "x": 938,
                "y": 268,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [844, 339, 955, 443],
                "x": 903,
                "y": 447,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [864, 250, 971, 350],
                "x": 914,
                "y": 354,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-6, 351, 117, 463],
                "x": 60,
                "y": 461,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [839, 379, 964, 466],
                "x": 906,
                "y": 473,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [31, 123, 158, 213],
                "x": 99,
                "y": 222,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [590, -28, 724, 73],
                "x": 654,
                "y": 81,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [539, 345, 663, 454],
                "x": 601,
                "y": 449,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [26, 298, 138, 381],
                "x": 81,
                "y": 388,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [48, 363, 181, 467],
                "x": 114,
                "y": 469,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [868, 196, 970, 291],
                "x": 918,
                "y": 297,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [807, 298, 932, 390],
                "x": 870,
                "y": 400,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [827, 280, 945, 380],
                "x": 885,
                "y": 378,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [8, 370, 138, 485],
                "x": 75,
                "y": 480,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [830, 384, 946, 487],
                "x": 883,
                "y": 477,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [71, 134, 182, 242],
                "x": 124,
                "y": 240,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [593, 0, 719, 112],
                "x": 662,
                "y": 103,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [522, 311, 628, 413],
                "x": 576,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [37, 304, 163, 391],
                "x": 102,
                "y": 396,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [73, 407, 212, 517],
                "x": 142,
                "y": 509,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [845, 224, 958, 328],
                "x": 898,
                "y": 320,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [768, 248, 888, 366],
                "x": 838,
                "y": 357,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [803, 298, 916, 405],
                "x": 857,
                "y": 399,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [25, 389, 148, 492],
                "x": 90,
                "y": 498,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [800, 384, 916, 474],
                "x": 860,
                "y": 481,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [95, 152, 207, 266],
                "x": 149,
                "y": 260,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [614, 19, 723, 134],
                "x": 670,
                "y": 126,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [486, 275, 613, 380],
                "x": 551,
                "y": 384,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [65, 290, 190, 400],
                "x": 122,
                "y": 400,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [119, 444, 228, 530],
                "x": 171,
                "y": 540,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [819, 236, 943, 343],
                "x": 877,
                "y": 339,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [755, 216, 859, 311],
                "x": 806,
                "y": 317,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [762, 325, 883, 418],
                "x": 828,
                "y": 419,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [43, 422, 156, 521],
                "x": 105,
                "y": 513,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [773, 394, 893, 481],
                "x": 837,
                "y": 485,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [116, 186, 234, 283],
                "x": 174,
                "y": 279,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [623, 58, 745, 158],
                "x": 677,
                "y": 148,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [456, 267, 594, 381],
                "x": 526,
                "y": 373,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [84, 297, 196, 402],
                "x": 142,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [140, 455, 261, 553],
                "x": 200,
                "y": 562,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [807, 255, 920, 363],
                "x": 857,
                "y": 354,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [714, 172, 844, 287],
                "x": 774,
                "y": 282,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [736, 338, 868, 444],
                "x": 800,
                "y": 436,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [53, 421, 177, 529],
                "x": 120,
                "y": 526,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [754, 396, 873, 486],
                "x": 813,
                "y": 489,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [144, 191, 251, 296],
                "x": 199,
                "y": 299,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [632, 68, 749, 175],
                "x": 685,
                "y": 171,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [440, 272, 557, 367],
                "x": 501,
                "y": 374,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [112, 313, 224, 411],
                "x": 163,
                "y": 404,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [170, 481, 293, 584],
                "x": 228,
                "y": 576,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [785, 269, 898, 354],
                "x": 837,
                "y": 364,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [687, 149, 800, 250],
                "x": 741,
                "y": 250,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [715, 356, 836, 456],
                "x": 771,
                "y": 451,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [83, 436, 191, 530],
                "x": 135,
                "y": 537,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [720, 398, 857, 491],
                "x": 790,
                "y": 494,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [161, 210, 287, 321],
                "x": 224,
                "y": 318,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [640, 86, 751, 198],
                "x": 693,
                "y": 195,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [409, 281, 528, 395],
                "x": 476,
                "y": 385,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [129, 304, 244, 403],
                "x": 183,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [207, 486, 307, 581],
                "x": 257,
                "y": 583,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [759, 261, 873, 373],
                "x": 816,
                "y": 371,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [655, 123, 766, 224],
                "x": 709,
                "y": 222,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [683, 367, 804, 455],
                "x": 742,
                "y": 464,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [95, 440, 203, 543],
                "x": 150,
                "y": 547,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [698, 400, 830, 497],
                "x": 767,
                "y": 499,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [194, 229, 317, 341],
                "x": 249,
                "y": 337,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [637, 113, 754, 222],
                "x": 700,
                "y": 218,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [396, 297, 505, 398],
                "x": 451,
                "y": 405,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [146, 296, 265, 409],
                "x": 204,
                "y": 400,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [222, 474, 347, 578],
                "x": 285,
                "y": 582,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [740, 285, 847, 379],
                "x": 796,
                "y": 375,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [621, 106, 737, 201],
                "x": 677,
                "y": 198,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [656, 373, 769, 484],
                "x": 714,
                "y": 475,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [96, 453, 232, 563],
                "x": 165,
                "y": 554,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [677, 399, 806, 508],
                "x": 744,
                "y": 505,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [224, 257, 325, 362],
                "x": 274,
                "y": 356,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [649, 142, 774, 239],
                "x": 708,
                "y": 242,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [376, 337, 480, 426],
                "x": 426,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [163, 303, 284, 386],
                "x": 224,
                "y": 396,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [260, 482, 381, 573],
                "x": 314,
                "y": 575,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [711, 277, 827, 385],
                "x": 776,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [578, 85, 713, 170],
                "x": 645,
                "y": 179,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [631, 392, 741, 493],
                "x": 685,
                "y": 484,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [122, 458, 234, 553],
                "x": 180,
                "y": 560,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [663, 403, 780, 518],
                "x": 720,
                "y": 510,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [243, 264, 358, 380],
                "x": 299,
                "y": 374,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [661, 161, 766, 261],
                "x": 716,
                "y": 266,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [333, 362, 457, 456],
                "x": 401,
                "y": 462,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [184, 292, 304, 390],
                "x": 244,
                "y": 391,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [274, 457, 405, 572],
                "x": 342,
                "y": 563,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [704, 283, 823, 370],
                "x": 755,
                "y": 374,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [551, 54, 679, 153],
                "x": 612,
                "y": 163,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [596, 395, 711, 501],
                "x": 657,
                "y": 492,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [125, 473, 257, 554],
                "x": 195,
                "y": 564,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [637, 417, 751, 523],
                "x": 697,
                "y": 516,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [261, 283, 381, 391],
                "x": 324,
                "y": 391,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [656, 187, 774, 290],
                "x": 723,
                "y": 290,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [317, 389, 443, 489],
                "x": 376,
                "y": 496,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [212, 285, 334, 384],
                "x": 265,
                "y": 384,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [315, 456, 438, 545],
                "x": 371,
                "y": 546,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [682, 272, 804, 370],
                "x": 735,
                "y": 370,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [528, 48, 640, 148],
                "x": 580,
                "y": 152,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [575, 403, 689, 489],
                "x": 628,
                "y": 498,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [157, 470, 278, 570],
                "x": 210,
                "y": 566,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [604, 420, 742, 519],
                "x": 674,
                "y": 521,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [281, 304, 403, 410],
                "x": 349,
                "y": 407,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [674, 214, 782, 304],
                "x": 731,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [283, 438, 414, 528],
                "x": 351,
                "y": 531,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [234, 272, 343, 384],
                "x": 285,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [340, 425, 459, 520],
                "x": 400,
                "y": 524,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [664, 258, 771, 361],
                "x": 715,
                "y": 364,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [481, 43, 611, 149],
                "x": 548,
                "y": 145,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [532, 392, 653, 495],
                "x": 600,
                "y": 502,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [173, 474, 295, 576],
                "x": 225,
                "y": 567,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [591, 436, 712, 520],
                "x": 651,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [316, 329, 443, 412],
                "x": 374,
                "y": 422,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [674, 231, 793, 336],
                "x": 739,
                "y": 337,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [262, 468, 392, 569],
                "x": 325,
                "y": 565,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [242, 264, 367, 371],
                "x": 306,
                "y": 367,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [365, 395, 483, 495],
                "x": 428,
                "y": 499,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [627, 264, 745, 363],
                "x": 694,
                "y": 356,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [457, 36, 566, 135],
                "x": 516,
                "y": 142,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [503, 397, 631, 511],
                "x": 571,
                "y": 504,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [173, 474, 295, 574],
                "x": 240,
                "y": 565,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [566, 437, 689, 532],
                "x": 627,
                "y": 533,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [334, 334, 467, 426],
                "x": 399,
                "y": 436,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [692, 256, 812, 356],
                "x": 746,
                "y": 361,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [234, 489, 365, 590],
                "x": 300,
                "y": 598,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [271, 260, 376, 360],
                "x": 326,
                "y": 358,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [395, 375, 527, 468],
                "x": 457,
                "y": 472,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [607, 244, 729, 342],
                "x": 674,
                "y": 347,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [433, 40, 548, 140],
                "x": 483,
                "y": 143,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [491, 410, 612, 499],
                "x": 542,
                "y": 506,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [194, 461, 319, 573],
                "x": 255,
                "y": 563,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [540, 434, 665, 548],
                "x": 604,
                "y": 538,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [362, 347, 484, 457],
                "x": 424,
                "y": 447,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [684, 283, 815, 394],
                "x": 754,
                "y": 384,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [213, 520, 325, 630],
                "x": 275,
                "y": 626,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [295, 254, 413, 358],
                "x": 346,
                "y": 348,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [417, 341, 541, 440],
                "x": 485,
                "y": 441,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [602, 228, 709, 334],
                "x": 654,
                "y": 336,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [400, 52, 501, 153],
                "x": 451,
                "y": 149,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [444, 401, 577, 497],
                "x": 514,
                "y": 505,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [201, 455, 338, 561],
                "x": 270,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [521, 452, 639, 535],
                "x": 581,
                "y": 544,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [394, 364, 504, 465],
                "x": 449,
                "y": 457,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [698, 314, 828, 406],
                "x": 762,
                "y": 407,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [188, 538, 318, 640],
                "x": 250,
                "y": 648,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [299, 230, 430, 327],
                "x": 367,
                "y": 337,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [458, 302, 584, 404],
                "x": 514,
                "y": 410,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [578, 233, 703, 328],
                "x": 633,
                "y": 326,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [353, 68, 477, 166],
                "x": 419,
                "y": 160,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [415, 411, 546, 501],
                "x": 485,
                "y": 504,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [225, 452, 344, 547],
                "x": 285,
                "y": 553,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [505, 439, 619, 551],
                "x": 558,
                "y": 549,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [410, 356, 541, 456],
                "x": 473,
                "y": 464,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [719, 333, 837, 420],
                "x": 769,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [166, 556, 283, 663],
                "x": 225,
                "y": 663,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [328, 219, 453, 325],
                "x": 387,
                "y": 325,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [474, 273, 609, 382],
                "x": 542,
                "y": 377,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [552, 216, 671, 304],
                "x": 613,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [331, 67, 450, 176],
                "x": 387,
                "y": 175,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [397, 403, 521, 506],
                "x": 457,
                "y": 501,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [230, 450, 361, 540],
                "x": 300,
                "y": 546,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [483, 461, 593, 552],
                "x": 534,
                "y": 554,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [442, 369, 550, 475],
                "x": 498,
                "y": 469,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [707, 359, 845, 460],
                "x": 777,
                "y": 452,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [139, 569, 253, 663],
                "x": 200,
                "y": 668,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [356, 214, 473, 308],
                "x": 408,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [519, 234, 626, 337],
                "x": 571,
                "y": 344,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [543, 205, 649, 313],
                "x": 593,
                "y": 303,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [304, 104, 424, 200],
                "x": 354,
                "y": 195,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [376, 396, 483, 497],
                "x": 428,
                "y": 497,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [261, 446, 374, 537],
                "x": 315,
                "y": 537,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [450, 460, 571, 559],
                "x": 511,
                "y": 559,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [457, 362, 592, 468],
                "x": 523,
                "y": 472,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [723, 382, 855, 466],
                "x": 785,
                "y": 474,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [121, 566, 235, 654],
                "x": 175,
                "y": 661,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [369, 203, 495, 293],
                "x": 428,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [543, 221, 655, 315],
                "x": 600,
                "y": 312,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [509, 194, 636, 293],
                "x": 572,
                "y": 292,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [256, 120, 378, 219],
                "x": 322,
                "y": 219,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [331, 398, 469, 494],
                "x": 400,
                "y": 491,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [260, 417, 400, 527],
                "x": 330,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [422, 471, 542, 563],
                "x": 488,
                "y": 564,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [495, 369, 618, 475],
                "x": 548,
                "y": 472,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [727, 392, 854, 496],
                "x": 792,
                "y": 495,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [99, 538, 203, 634],
                "x": 150,
                "y": 642,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [379, 195, 511, 282],
                "x": 448,
                "y": 290,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [559, 177, 693, 285],
                "x": 628,
                "y": 280,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [501, 189, 606, 289],
                "x": 552,
                "y": 282,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [231, 147, 350, 242],
                "x": 290,
                "y": 248,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [315, 394, 436, 495],
                "x": 371,
                "y": 485,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [295, 411, 400, 526],
                "x": 345,
                "y": 516,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [395, 467, 523, 566],
                "x": 465,
                "y": 568,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [507, 369, 640, 467],
                "x": 573,
                "y": 469,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [741, 411, 870, 526],
                "x": 800,
                "y": 516,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [60, 507, 180, 617],
                "x": 125,
                "y": 608,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [410, 181, 536, 278],
                "x": 469,
                "y": 279,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [594, 152, 726, 246],
                "x": 657,
                "y": 251,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [468, 175, 583, 276],
                "x": 531,
                "y": 273,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [199, 183, 311, 283],
                "x": 258,
                "y": 282,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [292, 369, 395, 488],
                "x": 342,
                "y": 478,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [309, 411, 413, 497],
                "x": 361,
                "y": 504,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [381, 474, 505, 579],
                "x": 441,
                "y": 573,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [532, 365, 654, 472],
                "x": 598,
                "y": 463,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [743, 428, 858, 531],
                "x": 808,
                "y": 536,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [35, 463, 150, 560],
                "x": 100,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [422, 157, 544, 275],
                "x": 489,
                "y": 267,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [627, 124, 752, 215],
                "x": 685,
                "y": 224,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [458, 175, 570, 272],
                "x": 511,
                "y": 265,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [172, 230, 280, 318],
                "x": 225,
                "y": 321,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [249, 363, 384, 471],
                "x": 314,
                "y": 469,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [313, 394, 440, 496],
                "x": 376,
                "y": 490,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [354, 485, 481, 573],
                "x": 418,
                "y": 576,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [554, 358, 676, 458],
                "x": 623,
                "y": 453,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [760, 451, 873, 556],
                "x": 815,
                "y": 555,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [12, 394, 125, 493],
                "x": 75,
                "y": 489,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [446, 153, 575, 260],
                "x": 510,
                "y": 257,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [648, 103, 777, 204],
                "x": 714,
                "y": 199,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [436, 154, 543, 268],
                "x": 491,
                "y": 259,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [140, 255, 255, 356],
                "x": 193,
                "y": 364,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [220, 368, 347, 460],
                "x": 285,
                "y": 460,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [339, 386, 450, 480],
                "x": 391,
                "y": 476,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [333, 488, 459, 571],
                "x": 395,
                "y": 580,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [578, 349, 703, 442],
                "x": 648,
                "y": 440,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [773, 477, 890, 578],
                "x": 823,
                "y": 574,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-18, 296, 113, 394],
                "x": 50,
                "y": 399,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [477, 139, 592, 248],
                "x": 530,
                "y": 246,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [672, 71, 798, 188],
                "x": 742,
                "y": 179,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [409, 149, 536, 261],
                "x": 470,
                "y": 254,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [100, 316, 217, 422],
                "x": 161,
                "y": 413,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [190, 350, 316, 447],
                "x": 257,
                "y": 451,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [343, 366, 468, 456],
                "x": 406,
                "y": 460,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [321, 478, 436, 579],
                "x": 372,
                "y": 582,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [610, 320, 733, 418],
                "x": 673,
                "y": 423,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [763, 496, 896, 589],
                "x": 831,
                "y": 592,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-31, 186, 93, 282],
                "x": 25,
                "y": 288,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [499, 130, 605, 232],
                "x": 551,
                "y": 237,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [714, 71, 831, 162],
                "x": 771,
                "y": 163,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [381, 151, 512, 255],
                "x": 450,
                "y": 252,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [64, 365, 189, 469],
                "x": 129,
                "y": 467,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [163, 332, 279, 432],
                "x": 228,
                "y": 440,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [360, 338, 488, 435],
                "x": 421,
                "y": 443,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [286, 477, 415, 592],
                "x": 348,
                "y": 585,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [647, 306, 762, 402],
                "x": 698,
                "y": 402,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [777, 517, 895, 615],
                "x": 838,
                "y": 608,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-56, 50, 62, 153],
                "x": 0,
                "y": 154,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [511, 122, 631, 224],
                "x": 571,
                "y": 228,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [747, 54, 857, 159],
                "x": 800,
                "y": 152,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [360, 144, 499, 256],
                "x": 430,
                "y": 253,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [45, 428, 159, 526],
                "x": 96,
                "y": 525,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [136, 327, 251, 435],
                "x": 200,
                "y": 429,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [383, 319, 503, 431],
                "x": 436,
                "y": 426,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [274, 493, 377, 584],
                "x": 325,
                "y": 586,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [671, 282, 773, 372],
                "x": 723,
                "y": 377,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [796, 518, 907, 615],
                "x": 846,
                "y": 624,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [539, 114, 648, 219],
                "x": 591,
                "y": 220,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [768, 41, 890, 137],
                "x": 828,
                "y": 147,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [348, 148, 462, 258],
                "x": 409,
                "y": 256,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-1, 488, 117, 599],
                "x": 64,
                "y": 589,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [102, 314, 239, 423],
                "x": 171,
                "y": 417,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [381, 313, 509, 416],
                "x": 451,
                "y": 407,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [252, 484, 368, 596],
                "x": 302,
                "y": 587,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [679, 255, 818, 341],
                "x": 748,
                "y": 347,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [788, 549, 907, 637],
                "x": 854,
                "y": 639,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [546, 118, 669, 212],
                "x": 612,
                "y": 213,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [787, 49, 912, 154],
                "x": 857,
                "y": 148,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [326, 158, 454, 255],
                "x": 389,
                "y": 263,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-22, 557, 84, 668],
                "x": 32,
                "y": 658,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [78, 305, 208, 415],
                "x": 142,
                "y": 405,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [412, 295, 535, 393],
                "x": 466,
                "y": 388,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [216, 493, 337, 580],
                "x": 279,
                "y": 588,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [708, 221, 829, 304],
                "x": 773,
                "y": 313,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [799, 555, 926, 659],
                "x": 861,
                "y": 653,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [571, 101, 690, 197],
                "x": 632,
                "y": 207,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [820, 66, 955, 166],
                "x": 885,
                "y": 156,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [301, 175, 433, 266],
                "x": 369,
                "y": 273,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-62, 626, 58, 728],
                "x": 0,
                "y": 733,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [49, 295, 170, 400],
                "x": 114,
                "y": 392,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [425, 263, 533, 367],
                "x": 481,
                "y": 367,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [197, 482, 324, 586],
                "x": 255,
                "y": 588,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [744, 182, 861, 280],
                "x": 798,
                "y": 274,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [802, 572, 934, 661],
                "x": 869,
                "y": 665,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [591, 112, 717, 197],
                "x": 653,
                "y": 203,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [848, 69, 983, 171],
                "x": 914,
                "y": 172,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [287, 190, 408, 283],
                "x": 348,
                "y": 288,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [33, 279, 136, 373],
                "x": 85,
                "y": 379,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [431, 249, 555, 344],
                "x": 496,
                "y": 346,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [173, 481, 288, 597],
                "x": 232,
                "y": 587,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [761, 125, 883, 225],
                "x": 823,
                "y": 230,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [808, 578, 933, 671],
                "x": 877,
                "y": 677,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [605, 102, 729, 194],
                "x": 673,
                "y": 201,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [885, 102, 1010, 199],
                "x": 942,
                "y": 196,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [277, 209, 386, 307],
                "x": 328,
                "y": 306,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [4, 261, 119, 364],
                "x": 57,
                "y": 366,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [450, 229, 579, 317],
                "x": 511,
                "y": 325,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [153, 483, 267, 585],
                "x": 209,
                "y": 585,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [787, 83, 918, 184],
                "x": 848,
                "y": 181,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [823, 595, 939, 697],
                "x": 884,
                "y": 687,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [624, 108, 757, 207],
                "x": 693,
                "y": 200,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [913, 131, 1038, 239],
                "x": 971,
                "y": 229,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [258, 234, 366, 320],
                "x": 308,
                "y": 330,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-24, 251, 90, 349],
                "x": 28,
                "y": 352,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [464, 196, 593, 308],
                "x": 526,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [126, 479, 241, 584],
                "x": 186,
                "y": 583,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [814, 24, 935, 123],
                "x": 873,
                "y": 126,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [824, 586, 945, 703],
                "x": 892,
                "y": 695,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [662, 90, 771, 210],
                "x": 714,
                "y": 200,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [935, 164, 1062, 270],
                "x": 1000,
                "y": 273,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [229, 252, 351, 357],
                "x": 287,
                "y": 358,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-64, 231, 50, 345],
                "x": 0,
                "y": 339,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [473, 175, 594, 286],
                "x": 541,
                "y": 279,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [94, 479, 221, 589],
                "x": 162,
                "y": 579,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [831, -31, 952, 64],
                "x": 898,
                "y": 66,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [842, 594, 958, 695],
                "x": 900,
                "y": 703,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [678, 99, 789, 210],
                "x": 734,
                "y": 203,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [209, 297, 324, 382],
                "x": 267,
                "y": 391,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [489, 148, 620, 251],
                "x": 556,
                "y": 256,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [87, 473, 202, 566],
                "x": 139,
                "y": 575,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [855, -110, 992, 10],
                "x": 923,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [848, 616, 972, 707],
                "x": 907,
                "y": 709,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [703, 105, 805, 212],
                "x": 755,
                "y": 208,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [195, 323, 302, 430],
                "x": 247,
                "y": 430,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [502, 141, 636, 231],
                "x": 571,
                "y": 231,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [53, 473, 180, 563],
                "x": 116,
                "y": 570,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [847, 620, 982, 706],
                "x": 915,
                "y": 713,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [713, 114, 836, 216],
                "x": 775,
                "y": 215,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [163, 384, 285, 465],
                "x": 226,
                "y": 475,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [535, 108, 656, 202],
                "x": 586,
                "y": 207,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [41, 464, 143, 557],
                "x": 93,
                "y": 564,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [867, 607, 978, 717],
                "x": 923,
                "y": 716,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [740, 133, 850, 232],
                "x": 795,
                "y": 224,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [138, 422, 274, 535],
                "x": 206,
                "y": 526,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [532, 72, 663, 172],
                "x": 601,
                "y": 182,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [12, 454, 120, 552],
                "x": 69,
                "y": 557,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [866, 614, 980, 722],
                "x": 930,
                "y": 717,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [755, 136, 872, 233],
                "x": 816,
                "y": 236,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [126, 485, 247, 583],
                "x": 186,
                "y": 584,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [564, 54, 683, 149],
                "x": 616,
                "y": 157,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-18, 447, 103, 541],
                "x": 46,
                "y": 548,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [874, 625, 995, 706],
                "x": 938,
                "y": 716,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [781, 159, 890, 254],
                "x": 836,
                "y": 250,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [100, 542, 216, 643],
                "x": 165,
                "y": 648,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [570, 34, 685, 125],
                "x": 631,
                "y": 131,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-46, 447, 85, 538],
                "x": 23,
                "y": 539,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [895, 607, 996, 709],
                "x": 946,
                "y": 714,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [806, 177, 923, 265],
                "x": 857,
                "y": 267,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [77, 625, 213, 725],
                "x": 145,
                "y": 720,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [581, 4, 715, 97],
                "x": 646,
                "y": 105,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-66, 429, 65, 526],
                "x": 0,
                "y": 529,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [901, 604, 1007, 701],
                "x": 953,
                "y": 710,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [823, 191, 942, 283],
                "x": 877,
                "y": 287,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [71, 700, 191, 806],
                "x": 125,
                "y": 800,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [606, -23, 714, 85],
                "x": 661,
                "y": 79,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [901, 614, 1030, 697],
                "x": 961,
                "y": 704,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [837, 200, 959, 305],
                "x": 897,
                "y": 310,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [606, -50, 738, 60],
                "x": 676,
                "y": 52,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [911, 601, 1038, 697],
                "x": 969,
                "y": 696,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [861, 236, 973, 333],
                "x": 918,
                "y": 336,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [628, -65, 758, 34],
                "x": 691,
                "y": 26,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [921, 591, 1037, 675],
                "x": 976,
                "y": 685,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [882, 275, 1008, 363],
                "x": 938,
                "y": 366,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [657, -94, 760, -5],
                "x": 707,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [921, 575, 1052, 677],
                "x": 984,
                "y": 673,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [896, 292, 1023, 390],
                "x": 959,
                "y": 399,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 49,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [924, 566, 1061, 659],
                "x": 992,
                "y": 659,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [909, 344, 1039, 435],
                "x": 979,
                "y": 435,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 50,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [935, 551, 1061, 644],
                "x": 1000,
                "y": 643,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [935, 386, 1055, 467],
                "x": 1000,
                "y": 476,
                "track_id": None,
            },
        ],
    },
]
