country_balls_amount = 5
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [708, -91, 811, 4],
                "x": 758,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-66, 400, 52, 505],
                "x": 0,
                "y": 505,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-63, 682, 58, 771],
                "x": 0,
                "y": 780,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [935, 531, 1063, 616],
                "x": 1000,
                "y": 623,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 1000, "y": 603, "track_id": None},
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [683, -57, 813, 46],
                "x": 752,
                "y": 37,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-28, 378, 96, 476],
                "x": 32,
                "y": 482,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-20, 584, 99, 671],
                "x": 44,
                "y": 681,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [935, 494, 1057, 604],
                "x": 999,
                "y": 604,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 967, "y": 402, "track_id": None},
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [694, -31, 813, 61],
                "x": 746,
                "y": 71,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [5, 376, 127, 471],
                "x": 64,
                "y": 466,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [30, 487, 151, 587],
                "x": 88,
                "y": 597,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [945, 479, 1051, 587],
                "x": 998,
                "y": 585,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [883, 160, 1003, 256],
                "x": 934,
                "y": 257,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [688, -1, 807, 96],
                "x": 740,
                "y": 103,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [41, 356, 147, 457],
                "x": 96,
                "y": 455,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [76, 422, 191, 533],
                "x": 132,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [929, 469, 1066, 562],
                "x": 997,
                "y": 567,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [831, 63, 954, 160],
                "x": 901,
                "y": 161,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [677, 36, 792, 122],
                "x": 734,
                "y": 132,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [68, 357, 179, 458],
                "x": 129,
                "y": 449,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [116, 379, 233, 463],
                "x": 176,
                "y": 469,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [929, 453, 1061, 549],
                "x": 996,
                "y": 548,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [806, 14, 918, 111],
                "x": 868,
                "y": 109,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [658, 68, 792, 155],
                "x": 728,
                "y": 158,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [96, 338, 229, 441],
                "x": 161,
                "y": 447,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [168, 312, 286, 411],
                "x": 220,
                "y": 421,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [938, 421, 1063, 538],
                "x": 995,
                "y": 529,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 835, "y": 94, "track_id": None},
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [667, 80, 784, 181],
                "x": 723,
                "y": 183,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [126, 340, 246, 447],
                "x": 193,
                "y": 449,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 265, "y": 382, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [935, 402, 1052, 505],
                "x": 994,
                "y": 511,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [748, 19, 868, 106],
                "x": 802,
                "y": 112,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [667, 110, 768, 196],
                "x": 717,
                "y": 205,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [162, 360, 282, 455],
                "x": 225,
                "y": 455,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 309, "y": 352, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [926, 402, 1055, 492],
                "x": 993,
                "y": 493,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [700, 46, 822, 151],
                "x": 769,
                "y": 156,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 711, "y": 224, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [206, 361, 323, 460],
                "x": 258,
                "y": 463,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [290, 233, 415, 319],
                "x": 353,
                "y": 328,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [927, 382, 1060, 467],
                "x": 993,
                "y": 475,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [671, 111, 790, 219],
                "x": 736,
                "y": 220,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 705, "y": 242, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [226, 377, 343, 480],
                "x": 290,
                "y": 473,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [338, 210, 449, 314],
                "x": 397,
                "y": 309,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 992, "y": 457, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [634, 205, 765, 292],
                "x": 703,
                "y": 298,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [639, 147, 762, 265],
                "x": 699,
                "y": 257,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [259, 392, 388, 484],
                "x": 322,
                "y": 486,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [391, 190, 497, 299],
                "x": 441,
                "y": 294,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [928, 333, 1058, 450],
                "x": 991,
                "y": 440,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [617, 277, 729, 381],
                "x": 670,
                "y": 386,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 694, "y": 270, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [292, 395, 411, 491],
                "x": 354,
                "y": 500,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [427, 185, 544, 274],
                "x": 486,
                "y": 282,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [922, 323, 1056, 426],
                "x": 990,
                "y": 422,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [574, 377, 688, 482],
                "x": 637,
                "y": 476,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [622, 177, 752, 271],
                "x": 688,
                "y": 281,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [319, 424, 444, 518],
                "x": 387,
                "y": 514,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [475, 164, 599, 280],
                "x": 530,
                "y": 271,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 989, "y": 405, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [547, 463, 658, 556],
                "x": 604,
                "y": 563,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [624, 192, 739, 295],
                "x": 682,
                "y": 291,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [362, 434, 472, 534],
                "x": 419,
                "y": 530,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [524, 161, 642, 253],
                "x": 574,
                "y": 259,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 988, "y": 388, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [518, 534, 639, 633],
                "x": 571,
                "y": 642,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [620, 193, 737, 305],
                "x": 676,
                "y": 298,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [392, 444, 505, 552],
                "x": 451,
                "y": 545,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [551, 153, 672, 237],
                "x": 618,
                "y": 246,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [930, 262, 1053, 361],
                "x": 987,
                "y": 371,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [472, 602, 592, 706],
                "x": 538,
                "y": 706,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [620, 203, 732, 295],
                "x": 670,
                "y": 304,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [430, 464, 536, 552],
                "x": 483,
                "y": 559,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [609, 136, 730, 229],
                "x": 662,
                "y": 230,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [935, 248, 1051, 364],
                "x": 986,
                "y": 354,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [438, 642, 567, 744],
                "x": 505,
                "y": 750,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [597, 209, 727, 307],
                "x": 664,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [464, 481, 578, 581],
                "x": 516,
                "y": 572,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [653, 111, 771, 208],
                "x": 707,
                "y": 210,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [925, 246, 1053, 341],
                "x": 986,
                "y": 337,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [406, 669, 540, 763],
                "x": 472,
                "y": 768,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [605, 206, 712, 319],
                "x": 659,
                "y": 310,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [493, 493, 609, 575],
                "x": 548,
                "y": 584,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [684, 80, 801, 180],
                "x": 751,
                "y": 185,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [920, 225, 1052, 316],
                "x": 985,
                "y": 321,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [375, 651, 498, 750],
                "x": 439,
                "y": 753,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [602, 210, 712, 300],
                "x": 653,
                "y": 310,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [526, 495, 649, 586],
                "x": 580,
                "y": 594,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [741, 48, 863, 150],
                "x": 795,
                "y": 152,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [916, 211, 1049, 300],
                "x": 984,
                "y": 305,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [350, 603, 474, 705],
                "x": 406,
                "y": 701,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [588, 202, 705, 306],
                "x": 647,
                "y": 309,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [553, 505, 663, 609],
                "x": 612,
                "y": 601,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [789, 19, 896, 118],
                "x": 839,
                "y": 111,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [915, 180, 1041, 288],
                "x": 983,
                "y": 288,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [318, 513, 431, 599],
                "x": 373,
                "y": 606,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [578, 215, 711, 315],
                "x": 641,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [585, 498, 709, 612],
                "x": 645,
                "y": 605,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [826, -47, 950, 64],
                "x": 883,
                "y": 61,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [920, 175, 1044, 281],
                "x": 982,
                "y": 272,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [290, 353, 400, 464],
                "x": 340,
                "y": 461,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [576, 205, 686, 306],
                "x": 635,
                "y": 303,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [612, 495, 745, 608],
                "x": 677,
                "y": 605,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [873, -107, 980, -10],
                "x": 928,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [918, 150, 1042, 267],
                "x": 981,
                "y": 257,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [244, 154, 374, 268],
                "x": 307,
                "y": 261,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [577, 201, 683, 308],
                "x": 630,
                "y": 298,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [642, 498, 774, 609],
                "x": 709,
                "y": 602,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [926, 139, 1038, 244],
                "x": 980,
                "y": 241,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [214, -97, 336, 8],
                "x": 274,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [556, 183, 675, 298],
                "x": 624,
                "y": 291,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [684, 496, 795, 584],
                "x": 741,
                "y": 594,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [913, 136, 1048, 221],
                "x": 979,
                "y": 226,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [563, 191, 684, 289],
                "x": 618,
                "y": 283,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [709, 490, 840, 576],
                "x": 774,
                "y": 581,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [923, 112, 1033, 215],
                "x": 979,
                "y": 210,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 612, "y": 275, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [752, 464, 856, 569],
                "x": 806,
                "y": 562,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [928, 85, 1032, 199],
                "x": 978,
                "y": 195,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [555, 172, 662, 261],
                "x": 606,
                "y": 265,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [779, 441, 890, 530],
                "x": 838,
                "y": 537,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [921, 73, 1029, 186],
                "x": 977,
                "y": 180,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [538, 152, 652, 249],
                "x": 601,
                "y": 254,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [816, 399, 926, 502],
                "x": 870,
                "y": 506,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [912, 64, 1028, 168],
                "x": 976,
                "y": 165,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [527, 146, 658, 252],
                "x": 595,
                "y": 242,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [837, 371, 955, 478],
                "x": 903,
                "y": 468,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [912, 44, 1044, 146],
                "x": 975,
                "y": 151,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [533, 122, 654, 231],
                "x": 589,
                "y": 229,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [879, 314, 996, 412],
                "x": 935,
                "y": 422,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [920, 39, 1036, 138],
                "x": 974,
                "y": 136,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [527, 121, 652, 206],
                "x": 583,
                "y": 216,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [910, 265, 1022, 375],
                "x": 967,
                "y": 369,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [921, 15, 1031, 130],
                "x": 973,
                "y": 122,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [510, 111, 634, 205],
                "x": 577,
                "y": 202,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [934, 216, 1070, 297],
                "x": 1000,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [908, 13, 1039, 118],
                "x": 972,
                "y": 108,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [512, 91, 621, 186],
                "x": 571,
                "y": 187,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [913, -5, 1038, 96],
                "x": 972,
                "y": 93,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [512, 74, 619, 163],
                "x": 566,
                "y": 171,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [904, -23, 1030, 76],
                "x": 971,
                "y": 80,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [499, 51, 614, 161],
                "x": 560,
                "y": 156,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [914, -31, 1031, 63],
                "x": 970,
                "y": 66,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [484, 34, 608, 129],
                "x": 554,
                "y": 139,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [900, -49, 1021, 44],
                "x": 969,
                "y": 52,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [495, 25, 611, 121],
                "x": 548,
                "y": 122,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [907, -70, 1031, 32],
                "x": 968,
                "y": 39,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [477, 7, 601, 95],
                "x": 542,
                "y": 105,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [913, -72, 1022, 16],
                "x": 967,
                "y": 26,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [471, -19, 606, 86],
                "x": 537,
                "y": 88,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [909, -84, 1029, 5],
                "x": 966,
                "y": 12,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [477, -35, 593, 79],
                "x": 531,
                "y": 70,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [910, -92, 1017, 7],
                "x": 966,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [474, -52, 589, 56],
                "x": 525,
                "y": 53,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [449, -63, 589, 33],
                "x": 519,
                "y": 35,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [445, -90, 580, 8],
                "x": 513,
                "y": 17,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [451, -99, 577, -8],
                "x": 508,
                "y": 0,
                "track_id": None,
            }
        ],
    },
]
