country_balls_amount = 5
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [941, 603, 1055, 702],
                "x": 1000,
                "y": 711,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [941, -64, 1052, 33],
                "x": 1000,
                "y": 30,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-59, 42, 64, 138],
                "x": 0,
                "y": 132,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [549, -110, 671, 9],
                "x": 604,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-57, 254, 56, 349],
                "x": 0,
                "y": 357,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [918, 593, 1040, 708],
                "x": 978,
                "y": 698,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [890, 63, 1020, 169],
                "x": 958,
                "y": 168,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-20, 18, 90, 129],
                "x": 30,
                "y": 128,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [533, -92, 643, 19],
                "x": 593,
                "y": 10,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-31, 275, 86, 358],
                "x": 26,
                "y": 368,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [891, 595, 1023, 689],
                "x": 957,
                "y": 685,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [847, 185, 967, 278],
                "x": 916,
                "y": 282,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-8, 30, 123, 131],
                "x": 61,
                "y": 130,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [518, -76, 635, 29],
                "x": 582,
                "y": 22,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-10, 281, 115, 380],
                "x": 52,
                "y": 376,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [868, 571, 1003, 680],
                "x": 936,
                "y": 671,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [809, 272, 940, 377],
                "x": 875,
                "y": 372,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [29, 28, 150, 132],
                "x": 92,
                "y": 137,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [508, -61, 641, 40],
                "x": 571,
                "y": 36,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [25, 282, 142, 387],
                "x": 78,
                "y": 383,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 914, "y": 657, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [773, 339, 900, 439],
                "x": 833,
                "y": 440,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [68, 54, 180, 157],
                "x": 122,
                "y": 149,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [508, -56, 620, 54],
                "x": 560,
                "y": 53,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [45, 280, 160, 390],
                "x": 105,
                "y": 388,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [834, 545, 945, 639],
                "x": 893,
                "y": 642,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [728, 393, 848, 497],
                "x": 791,
                "y": 488,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [94, 58, 212, 170],
                "x": 153,
                "y": 166,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [483, -36, 611, 71],
                "x": 549,
                "y": 70,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [64, 284, 197, 392],
                "x": 131,
                "y": 391,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [810, 519, 928, 617],
                "x": 872,
                "y": 627,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [696, 424, 820, 522],
                "x": 750,
                "y": 518,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [125, 89, 252, 183],
                "x": 184,
                "y": 186,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 539, "y": 90, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [103, 293, 216, 395],
                "x": 157,
                "y": 392,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [787, 514, 914, 605],
                "x": 851,
                "y": 612,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [642, 439, 758, 542],
                "x": 708,
                "y": 532,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [157, 121, 274, 221],
                "x": 214,
                "y": 211,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [462, 7, 589, 116],
                "x": 528,
                "y": 110,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [115, 295, 241, 388],
                "x": 184,
                "y": 392,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [778, 497, 892, 590],
                "x": 829,
                "y": 596,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [597, 425, 735, 540],
                "x": 666,
                "y": 532,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [195, 136, 304, 249],
                "x": 245,
                "y": 239,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [454, 34, 573, 121],
                "x": 517,
                "y": 131,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [152, 284, 265, 388],
                "x": 210,
                "y": 391,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [748, 489, 877, 570],
                "x": 808,
                "y": 580,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [560, 415, 683, 514],
                "x": 625,
                "y": 520,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [206, 163, 334, 276],
                "x": 276,
                "y": 270,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [455, 56, 568, 150],
                "x": 506,
                "y": 153,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [176, 286, 303, 392],
                "x": 236,
                "y": 388,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [732, 456, 837, 571],
                "x": 787,
                "y": 564,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [533, 398, 639, 487],
                "x": 583,
                "y": 497,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [251, 206, 359, 313],
                "x": 306,
                "y": 304,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [436, 83, 555, 177],
                "x": 495,
                "y": 175,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [199, 283, 326, 382],
                "x": 263,
                "y": 384,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [696, 445, 834, 550],
                "x": 765,
                "y": 548,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [483, 358, 604, 458],
                "x": 541,
                "y": 465,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [279, 244, 401, 331],
                "x": 337,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [425, 96, 539, 204],
                "x": 484,
                "y": 198,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [234, 285, 353, 368],
                "x": 289,
                "y": 378,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [692, 432, 807, 536],
                "x": 744,
                "y": 531,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [449, 330, 558, 425],
                "x": 500,
                "y": 427,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 368, "y": 379, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [409, 128, 530, 227],
                "x": 474,
                "y": 220,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [255, 265, 369, 377],
                "x": 315,
                "y": 372,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [661, 414, 787, 520],
                "x": 723,
                "y": 515,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [407, 274, 514, 392],
                "x": 458,
                "y": 384,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [345, 328, 460, 412],
                "x": 398,
                "y": 419,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [405, 152, 531, 245],
                "x": 463,
                "y": 242,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [279, 272, 401, 367],
                "x": 342,
                "y": 365,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [638, 408, 764, 498],
                "x": 702,
                "y": 499,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 416, "y": 339, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [364, 358, 499, 466],
                "x": 429,
                "y": 460,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [386, 166, 511, 270],
                "x": 452,
                "y": 264,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [305, 263, 434, 358],
                "x": 368,
                "y": 358,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [616, 392, 746, 485],
                "x": 680,
                "y": 483,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [305, 199, 425, 295],
                "x": 375,
                "y": 292,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [395, 410, 523, 507],
                "x": 460,
                "y": 503,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [391, 195, 498, 288],
                "x": 441,
                "y": 285,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [339, 252, 460, 358],
                "x": 394,
                "y": 349,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [609, 363, 711, 463],
                "x": 659,
                "y": 468,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [270, 143, 383, 245],
                "x": 333,
                "y": 246,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [428, 445, 544, 552],
                "x": 490,
                "y": 546,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [373, 214, 490, 298],
                "x": 430,
                "y": 306,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [358, 234, 473, 334],
                "x": 421,
                "y": 341,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [588, 346, 693, 446],
                "x": 638,
                "y": 453,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [241, 103, 344, 209],
                "x": 291,
                "y": 203,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [455, 486, 589, 598],
                "x": 521,
                "y": 590,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [365, 224, 473, 319],
                "x": 420,
                "y": 325,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [385, 237, 516, 326],
                "x": 447,
                "y": 332,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [557, 342, 674, 431],
                "x": 617,
                "y": 438,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [194, 57, 313, 160],
                "x": 250,
                "y": 164,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [489, 529, 607, 627],
                "x": 552,
                "y": 633,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [340, 252, 462, 350],
                "x": 409,
                "y": 342,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [409, 222, 537, 332],
                "x": 473,
                "y": 322,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [540, 315, 650, 418],
                "x": 595,
                "y": 423,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [149, 27, 260, 129],
                "x": 208,
                "y": 133,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [530, 582, 643, 671],
                "x": 582,
                "y": 676,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [334, 254, 466, 355],
                "x": 398,
                "y": 358,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 499, "y": 313, "track_id": None},
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [516, 305, 629, 416],
                "x": 574,
                "y": 410,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [108, 11, 223, 100],
                "x": 166,
                "y": 109,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [555, 611, 674, 714],
                "x": 613,
                "y": 718,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [333, 279, 442, 367],
                "x": 387,
                "y": 373,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [465, 196, 593, 307],
                "x": 526,
                "y": 304,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [500, 296, 608, 389],
                "x": 553,
                "y": 396,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [60, 4, 176, 101],
                "x": 125,
                "y": 96,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [580, 667, 696, 751],
                "x": 644,
                "y": 760,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [313, 286, 430, 376],
                "x": 376,
                "y": 385,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [491, 198, 618, 287],
                "x": 552,
                "y": 294,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [469, 289, 599, 390],
                "x": 531,
                "y": 384,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [18, -6, 144, 88],
                "x": 83,
                "y": 95,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [605, 696, 727, 801],
                "x": 675,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [297, 289, 430, 395],
                "x": 365,
                "y": 395,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [511, 179, 638, 279],
                "x": 578,
                "y": 285,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [454, 271, 573, 366],
                "x": 510,
                "y": 372,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-20, -2, 100, 101],
                "x": 41,
                "y": 108,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [300, 302, 420, 398],
                "x": 355,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [550, 175, 660, 280],
                "x": 605,
                "y": 277,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [419, 268, 541, 356],
                "x": 489,
                "y": 361,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-65, 41, 68, 130],
                "x": 0,
                "y": 137,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [277, 317, 407, 399],
                "x": 344,
                "y": 407,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [580, 176, 693, 264],
                "x": 631,
                "y": 269,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [406, 252, 520, 346],
                "x": 468,
                "y": 350,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [283, 315, 385, 402],
                "x": 333,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [598, 171, 720, 256],
                "x": 657,
                "y": 261,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [394, 251, 499, 346],
                "x": 446,
                "y": 341,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [271, 308, 388, 411],
                "x": 322,
                "y": 408,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [616, 148, 747, 248],
                "x": 684,
                "y": 255,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [373, 238, 489, 343],
                "x": 425,
                "y": 333,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [245, 309, 374, 413],
                "x": 311,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [657, 142, 763, 241],
                "x": 710,
                "y": 249,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [336, 217, 460, 320],
                "x": 404,
                "y": 325,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [242, 292, 359, 397],
                "x": 301,
                "y": 395,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [676, 143, 801, 245],
                "x": 736,
                "y": 244,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [316, 209, 442, 312],
                "x": 382,
                "y": 319,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [231, 288, 355, 391],
                "x": 290,
                "y": 383,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [700, 135, 826, 233],
                "x": 763,
                "y": 241,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [306, 224, 415, 305],
                "x": 361,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [228, 259, 336, 367],
                "x": 279,
                "y": 366,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [737, 145, 859, 230],
                "x": 789,
                "y": 238,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [274, 201, 394, 309],
                "x": 340,
                "y": 311,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [203, 240, 331, 350],
                "x": 268,
                "y": 346,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [759, 142, 872, 247],
                "x": 815,
                "y": 237,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [258, 199, 375, 315],
                "x": 319,
                "y": 308,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [207, 222, 308, 317],
                "x": 257,
                "y": 321,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [776, 128, 899, 231],
                "x": 842,
                "y": 238,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [238, 213, 366, 315],
                "x": 297,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [189, 194, 301, 299],
                "x": 246,
                "y": 291,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [813, 139, 928, 244],
                "x": 868,
                "y": 240,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [218, 218, 343, 302],
                "x": 276,
                "y": 308,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [167, 165, 289, 259],
                "x": 236,
                "y": 256,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [828, 137, 952, 249],
                "x": 894,
                "y": 244,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [196, 220, 313, 304],
                "x": 255,
                "y": 310,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [158, 109, 294, 209],
                "x": 225,
                "y": 216,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [869, 153, 990, 254],
                "x": 921,
                "y": 249,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 234, "y": 313, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [156, 61, 284, 165],
                "x": 214,
                "y": 171,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [880, 166, 1003, 250],
                "x": 947,
                "y": 257,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [150, 224, 276, 327],
                "x": 212,
                "y": 319,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [136, 26, 262, 114],
                "x": 203,
                "y": 120,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [915, 173, 1034, 268],
                "x": 973,
                "y": 267,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [133, 226, 256, 324],
                "x": 191,
                "y": 326,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [129, -31, 255, 70],
                "x": 192,
                "y": 63,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [939, 179, 1059, 285],
                "x": 1000,
                "y": 278,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [119, 228, 220, 340],
                "x": 170,
                "y": 335,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 182, "y": 0, "track_id": None},
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [83, 242, 200, 346],
                "x": 148,
                "y": 345,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [67, 262, 191, 354],
                "x": 127,
                "y": 358,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [48, 272, 166, 369],
                "x": 106,
                "y": 372,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [24, 283, 139, 388],
                "x": 85,
                "y": 389,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [0, 317, 124, 401],
                "x": 63,
                "y": 408,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-18, 327, 110, 434],
                "x": 42,
                "y": 429,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 47,
        "data": [{"cb_id": 0, "bounding_box": [], "x": 21, "y": 452, "track_id": None}],
    },
    {
        "frame_id": 48,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-58, 375, 53, 484],
                "x": 0,
                "y": 478,
                "track_id": None,
            }
        ],
    },
]
