country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [873, 701, 1004, 797],
                "x": 942,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-51, -18, 55, 73],
                "x": 0,
                "y": 75,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-58, 241, 62, 336],
                "x": 0,
                "y": 344,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [936, 547, 1069, 655],
                "x": 1000,
                "y": 657,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [947, -37, 1052, 62],
                "x": 1000,
                "y": 70,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [939, 512, 1070, 609],
                "x": 1000,
                "y": 613,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 618, "y": 0, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [-59, 612, 68, 718],
                "x": 0,
                "y": 708,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-61, 346, 56, 440],
                "x": 0,
                "y": 449,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [920, -110, 1051, -1],
                "x": 989,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [873, 701, 999, 805],
                "x": 943,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-34, -5, 87, 89],
                "x": 24,
                "y": 97,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-38, 183, 73, 281],
                "x": 22,
                "y": 281,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [923, 593, 1037, 692],
                "x": 977,
                "y": 689,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [933, 13, 1053, 114],
                "x": 985,
                "y": 106,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [926, 476, 1048, 560],
                "x": 993,
                "y": 569,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [574, -81, 701, 11],
                "x": 632,
                "y": 10,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-25, 591, 89, 678],
                "x": 26,
                "y": 681,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-40, 366, 86, 464],
                "x": 21,
                "y": 472,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [893, -56, 1027, 44],
                "x": 961,
                "y": 37,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [889, 689, 1014, 799],
                "x": 944,
                "y": 798,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-19, 10, 108, 109],
                "x": 49,
                "y": 118,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-9, 118, 115, 230],
                "x": 45,
                "y": 228,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 955, "y": 715, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [905, 48, 1037, 146],
                "x": 971,
                "y": 142,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [931, 425, 1046, 533],
                "x": 987,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [593, -73, 711, 17],
                "x": 647,
                "y": 21,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-18, 548, 118, 663],
                "x": 52,
                "y": 655,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 42, "y": 492, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [875, -30, 992, 66],
                "x": 934,
                "y": 72,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [880, 704, 1013, 791],
                "x": 945,
                "y": 797,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [6, 33, 130, 145],
                "x": 74,
                "y": 140,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 68, "y": 184, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [882, 634, 992, 733],
                "x": 933,
                "y": 736,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [906, 81, 1021, 168],
                "x": 957,
                "y": 175,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [930, 383, 1038, 481],
                "x": 980,
                "y": 486,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [596, -62, 726, 31],
                "x": 662,
                "y": 34,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [23, 520, 138, 618],
                "x": 78,
                "y": 627,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [-6, 402, 125, 498],
                "x": 63,
                "y": 508,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 906, "y": 105, "track_id": None},
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 946, "y": 797, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [48, 66, 165, 169],
                "x": 99,
                "y": 161,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [35, 43, 149, 155],
                "x": 90,
                "y": 149,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [851, 654, 965, 756],
                "x": 911,
                "y": 751,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [886, 99, 1004, 200],
                "x": 943,
                "y": 206,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [920, 352, 1034, 456],
                "x": 974,
                "y": 447,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [623, -56, 745, 45],
                "x": 676,
                "y": 48,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [40, 491, 163, 603],
                "x": 105,
                "y": 600,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [16, 429, 153, 531],
                "x": 85,
                "y": 522,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [819, 36, 939, 137],
                "x": 879,
                "y": 135,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [877, 703, 1016, 787],
                "x": 947,
                "y": 796,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [59, 72, 186, 191],
                "x": 124,
                "y": 181,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [55, 29, 170, 130],
                "x": 113,
                "y": 121,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [820, 666, 947, 756],
                "x": 888,
                "y": 761,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [869, 137, 992, 233],
                "x": 929,
                "y": 235,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [907, 319, 1024, 407],
                "x": 968,
                "y": 410,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [635, -39, 760, 63],
                "x": 691,
                "y": 62,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [73, 480, 181, 581],
                "x": 131,
                "y": 572,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [42, 439, 170, 543],
                "x": 106,
                "y": 533,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [795, 67, 916, 163],
                "x": 851,
                "y": 164,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [880, 686, 1015, 785],
                "x": 949,
                "y": 795,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [84, 90, 205, 197],
                "x": 149,
                "y": 200,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [80, -4, 187, 112],
                "x": 136,
                "y": 102,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [796, 671, 935, 758],
                "x": 866,
                "y": 767,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [846, 170, 976, 258],
                "x": 915,
                "y": 262,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [906, 266, 1013, 381],
                "x": 961,
                "y": 375,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [642, -25, 776, 78],
                "x": 706,
                "y": 78,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [88, 455, 225, 535],
                "x": 157,
                "y": 545,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [57, 448, 192, 533],
                "x": 127,
                "y": 541,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [761, 94, 889, 182],
                "x": 824,
                "y": 191,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [889, 684, 1012, 797],
                "x": 950,
                "y": 794,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [117, 110, 233, 223],
                "x": 173,
                "y": 219,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [94, -4, 224, 97],
                "x": 159,
                "y": 89,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [787, 662, 901, 759],
                "x": 844,
                "y": 768,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [834, 180, 963, 285],
                "x": 901,
                "y": 288,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [886, 232, 1013, 337],
                "x": 955,
                "y": 342,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [654, 2, 783, 103],
                "x": 720,
                "y": 94,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [133, 412, 251, 512],
                "x": 184,
                "y": 518,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [84, 438, 209, 552],
                "x": 148,
                "y": 547,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [732, 111, 865, 220],
                "x": 796,
                "y": 216,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [893, 702, 1018, 803],
                "x": 951,
                "y": 794,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [146, 142, 268, 227],
                "x": 198,
                "y": 237,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [129, -9, 239, 89],
                "x": 181,
                "y": 83,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [753, 659, 889, 757],
                "x": 822,
                "y": 765,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [837, 220, 948, 313],
                "x": 887,
                "y": 311,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [887, 219, 1005, 304],
                "x": 949,
                "y": 311,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [667, 11, 799, 107],
                "x": 735,
                "y": 110,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [146, 390, 261, 497],
                "x": 210,
                "y": 491,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [112, 449, 230, 555],
                "x": 170,
                "y": 550,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [699, 140, 832, 239],
                "x": 769,
                "y": 239,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [902, 694, 1012, 792],
                "x": 952,
                "y": 793,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [173, 157, 281, 257],
                "x": 223,
                "y": 253,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [148, -19, 268, 81],
                "x": 204,
                "y": 83,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [750, 657, 868, 748],
                "x": 800,
                "y": 758,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [820, 225, 939, 332],
                "x": 873,
                "y": 332,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [881, 180, 1007, 274],
                "x": 942,
                "y": 281,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [695, 29, 805, 119],
                "x": 750,
                "y": 127,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [166, 372, 300, 465],
                "x": 236,
                "y": 465,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [124, 446, 243, 556],
                "x": 191,
                "y": 551,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [672, 163, 811, 251],
                "x": 741,
                "y": 260,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [899, 700, 1014, 782],
                "x": 953,
                "y": 792,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [190, 166, 303, 264],
                "x": 248,
                "y": 269,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [169, -6, 283, 89],
                "x": 227,
                "y": 88,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [727, 656, 827, 740],
                "x": 777,
                "y": 747,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [802, 261, 929, 359],
                "x": 859,
                "y": 352,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [885, 148, 1005, 260],
                "x": 936,
                "y": 253,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [713, 49, 817, 141],
                "x": 764,
                "y": 145,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [208, 338, 318, 429],
                "x": 263,
                "y": 439,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [145, 450, 269, 546],
                "x": 212,
                "y": 550,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [663, 182, 765, 279],
                "x": 714,
                "y": 280,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [891, 695, 1014, 798],
                "x": 955,
                "y": 792,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [222, 183, 329, 290],
                "x": 273,
                "y": 284,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [199, -3, 307, 90],
                "x": 250,
                "y": 99,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [693, 632, 814, 733],
                "x": 755,
                "y": 733,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [784, 269, 897, 372],
                "x": 845,
                "y": 369,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 929, "y": 227, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [729, 68, 847, 169],
                "x": 779,
                "y": 162,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [225, 318, 349, 410],
                "x": 289,
                "y": 415,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [184, 443, 301, 546],
                "x": 234,
                "y": 547,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [621, 193, 754, 294],
                "x": 686,
                "y": 299,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 956, "y": 791, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [238, 193, 354, 299],
                "x": 298,
                "y": 297,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [212, 12, 324, 109],
                "x": 272,
                "y": 114,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [682, 617, 789, 721],
                "x": 733,
                "y": 716,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [764, 294, 889, 393],
                "x": 831,
                "y": 385,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [866, 92, 980, 194],
                "x": 923,
                "y": 202,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [738, 82, 847, 174],
                "x": 794,
                "y": 179,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [255, 299, 379, 384],
                "x": 315,
                "y": 391,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [188, 450, 318, 546],
                "x": 255,
                "y": 543,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [600, 210, 722, 305],
                "x": 659,
                "y": 315,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [900, 694, 1019, 788],
                "x": 957,
                "y": 790,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [258, 210, 373, 315],
                "x": 322,
                "y": 309,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [227, 43, 354, 126],
                "x": 295,
                "y": 134,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [641, 590, 772, 687],
                "x": 711,
                "y": 697,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [766, 290, 871, 401],
                "x": 817,
                "y": 398,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [851, 81, 979, 180],
                "x": 917,
                "y": 179,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [740, 93, 859, 199],
                "x": 809,
                "y": 197,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [280, 264, 396, 374],
                "x": 342,
                "y": 369,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [211, 430, 333, 534],
                "x": 276,
                "y": 536,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [579, 241, 689, 326],
                "x": 631,
                "y": 331,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [906, 698, 1028, 781],
                "x": 958,
                "y": 790,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [293, 209, 399, 309],
                "x": 347,
                "y": 319,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [257, 66, 375, 156],
                "x": 318,
                "y": 157,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [631, 570, 749, 666],
                "x": 688,
                "y": 674,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [737, 315, 855, 416],
                "x": 802,
                "y": 410,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [841, 63, 972, 153],
                "x": 910,
                "y": 158,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [768, 105, 886, 223],
                "x": 823,
                "y": 214,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [318, 243, 419, 342],
                "x": 368,
                "y": 348,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [229, 424, 348, 521],
                "x": 297,
                "y": 528,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [544, 246, 657, 340],
                "x": 604,
                "y": 345,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 959, "y": 789, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [306, 231, 439, 332],
                "x": 372,
                "y": 328,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [274, 84, 395, 174],
                "x": 340,
                "y": 183,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [598, 540, 718, 642],
                "x": 666,
                "y": 650,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [724, 319, 840, 411],
                "x": 788,
                "y": 419,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 904, "y": 138, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 838, "y": 230, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [325, 229, 463, 327],
                "x": 394,
                "y": 329,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [269, 420, 381, 509],
                "x": 319,
                "y": 519,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [512, 250, 641, 362],
                "x": 576,
                "y": 358,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [896, 685, 1017, 780],
                "x": 960,
                "y": 788,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [339, 231, 448, 330],
                "x": 397,
                "y": 335,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [298, 104, 413, 216],
                "x": 363,
                "y": 211,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [575, 526, 703, 629],
                "x": 644,
                "y": 623,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [719, 323, 826, 435],
                "x": 774,
                "y": 427,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [844, 16, 949, 123],
                "x": 898,
                "y": 119,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [794, 137, 923, 255],
                "x": 853,
                "y": 246,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [369, 203, 474, 314],
                "x": 421,
                "y": 312,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [283, 414, 397, 511],
                "x": 340,
                "y": 508,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [495, 276, 613, 375],
                "x": 549,
                "y": 369,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [896, 689, 1016, 795],
                "x": 962,
                "y": 788,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [372, 245, 491, 340],
                "x": 422,
                "y": 341,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [333, 138, 452, 232],
                "x": 386,
                "y": 242,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [569, 499, 681, 590],
                "x": 622,
                "y": 595,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [702, 333, 820, 423],
                "x": 760,
                "y": 432,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [823, 9, 954, 100],
                "x": 891,
                "y": 102,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [809, 172, 931, 263],
                "x": 867,
                "y": 262,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [395, 187, 502, 297],
                "x": 447,
                "y": 297,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [309, 390, 413, 503],
                "x": 361,
                "y": 497,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [470, 272, 577, 382],
                "x": 521,
                "y": 380,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [905, 678, 1033, 777],
                "x": 963,
                "y": 787,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [377, 245, 505, 335],
                "x": 447,
                "y": 345,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [359, 179, 468, 280],
                "x": 409,
                "y": 274,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [548, 455, 651, 568],
                "x": 600,
                "y": 565,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [683, 334, 800, 436],
                "x": 746,
                "y": 436,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [816, -7, 941, 87],
                "x": 885,
                "y": 87,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [831, 180, 932, 274],
                "x": 882,
                "y": 277,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [405, 184, 537, 282],
                "x": 473,
                "y": 283,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [331, 377, 447, 484],
                "x": 382,
                "y": 484,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [444, 281, 546, 394],
                "x": 494,
                "y": 390,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [896, 696, 1031, 780],
                "x": 964,
                "y": 787,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [409, 257, 531, 357],
                "x": 471,
                "y": 347,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [378, 201, 488, 306],
                "x": 431,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [524, 439, 642, 540],
                "x": 577,
                "y": 534,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [669, 330, 785, 434],
                "x": 732,
                "y": 437,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [814, -24, 933, 67],
                "x": 879,
                "y": 72,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [829, 184, 954, 300],
                "x": 897,
                "y": 291,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 499, "y": 273, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [339, 363, 467, 480],
                "x": 404,
                "y": 471,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [416, 293, 531, 393],
                "x": 467,
                "y": 398,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [911, 683, 1023, 788],
                "x": 965,
                "y": 786,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [427, 239, 564, 343],
                "x": 496,
                "y": 346,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [404, 237, 515, 350],
                "x": 454,
                "y": 341,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [490, 405, 620, 510],
                "x": 555,
                "y": 502,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [649, 347, 780, 446],
                "x": 718,
                "y": 437,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [818, -39, 929, 68],
                "x": 872,
                "y": 60,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [845, 204, 971, 313],
                "x": 911,
                "y": 304,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [474, 163, 591, 272],
                "x": 526,
                "y": 264,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [375, 358, 487, 459],
                "x": 425,
                "y": 457,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [372, 296, 492, 406],
                "x": 439,
                "y": 406,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [915, 690, 1027, 776],
                "x": 966,
                "y": 785,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [456, 254, 587, 352],
                "x": 521,
                "y": 344,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [424, 271, 536, 371],
                "x": 477,
                "y": 375,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [478, 367, 601, 463],
                "x": 533,
                "y": 469,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 704, "y": 434, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [804, -51, 929, 54],
                "x": 866,
                "y": 48,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [858, 219, 989, 325],
                "x": 926,
                "y": 315,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [482, 168, 620, 252],
                "x": 552,
                "y": 259,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [385, 345, 502, 436],
                "x": 446,
                "y": 442,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [357, 319, 480, 417],
                "x": 412,
                "y": 413,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [904, 680, 1030, 794],
                "x": 968,
                "y": 785,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [492, 244, 596, 349],
                "x": 546,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [444, 314, 553, 413],
                "x": 500,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [453, 341, 566, 429],
                "x": 511,
                "y": 437,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [627, 338, 742, 436],
                "x": 690,
                "y": 430,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 859, "y": 38, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [876, 220, 1004, 336],
                "x": 941,
                "y": 326,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [511, 154, 641, 249],
                "x": 578,
                "y": 256,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [406, 327, 525, 431],
                "x": 468,
                "y": 427,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [319, 320, 444, 422],
                "x": 384,
                "y": 420,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [906, 674, 1039, 790],
                "x": 969,
                "y": 784,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [514, 240, 626, 329],
                "x": 571,
                "y": 333,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [472, 341, 583, 434],
                "x": 522,
                "y": 441,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [431, 301, 556, 410],
                "x": 488,
                "y": 404,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [624, 318, 728, 423],
                "x": 676,
                "y": 423,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [793, -64, 905, 38],
                "x": 853,
                "y": 29,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [905, 228, 1010, 339],
                "x": 955,
                "y": 335,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [537, 161, 666, 256],
                "x": 605,
                "y": 256,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [438, 309, 544, 403],
                "x": 489,
                "y": 412,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [299, 321, 422, 417],
                "x": 357,
                "y": 426,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [912, 686, 1034, 780],
                "x": 970,
                "y": 784,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [539, 219, 658, 316],
                "x": 596,
                "y": 324,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [477, 377, 598, 472],
                "x": 545,
                "y": 472,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [396, 272, 516, 361],
                "x": 466,
                "y": 371,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [609, 324, 717, 418],
                "x": 662,
                "y": 415,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [797, -72, 909, 19],
                "x": 847,
                "y": 21,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [907, 251, 1037, 336],
                "x": 970,
                "y": 342,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [581, 157, 681, 251],
                "x": 631,
                "y": 259,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [445, 302, 560, 400],
                "x": 510,
                "y": 397,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 329, "y": 431, "track_id": None},
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [906, 679, 1024, 789],
                "x": 971,
                "y": 783,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [555, 212, 677, 303],
                "x": 620,
                "y": 313,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [504, 404, 638, 510],
                "x": 568,
                "y": 502,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [386, 247, 500, 328],
                "x": 444,
                "y": 338,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [580, 313, 716, 413],
                "x": 648,
                "y": 404,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [788, -92, 900, 16],
                "x": 840,
                "y": 15,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [925, 254, 1047, 341],
                "x": 985,
                "y": 348,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [597, 169, 723, 275],
                "x": 657,
                "y": 266,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [479, 288, 591, 373],
                "x": 531,
                "y": 382,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [252, 345, 356, 430],
                "x": 302,
                "y": 436,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [913, 677, 1038, 791],
                "x": 972,
                "y": 783,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [592, 203, 707, 297],
                "x": 645,
                "y": 299,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [538, 437, 652, 528],
                "x": 590,
                "y": 529,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [365, 197, 482, 302],
                "x": 422,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [564, 289, 696, 385],
                "x": 634,
                "y": 392,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [781, -97, 902, 20],
                "x": 834,
                "y": 10,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [933, 244, 1069, 363],
                "x": 1000,
                "y": 353,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [628, 169, 753, 277],
                "x": 684,
                "y": 276,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [496, 275, 606, 369],
                "x": 553,
                "y": 368,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 274, "y": 440, "track_id": None},
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [909, 689, 1034, 775],
                "x": 973,
                "y": 782,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [610, 173, 735, 272],
                "x": 670,
                "y": 282,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [560, 444, 667, 543],
                "x": 613,
                "y": 552,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [347, 183, 457, 280],
                "x": 400,
                "y": 276,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [551, 269, 689, 377],
                "x": 619,
                "y": 377,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [760, -105, 895, 0],
                "x": 828,
                "y": 5,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [652, 181, 764, 294],
                "x": 710,
                "y": 289,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [511, 256, 625, 364],
                "x": 574,
                "y": 354,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [184, 338, 314, 440],
                "x": 247,
                "y": 444,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [920, 689, 1030, 790],
                "x": 975,
                "y": 781,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [627, 158, 756, 273],
                "x": 695,
                "y": 263,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [570, 476, 690, 573],
                "x": 636,
                "y": 573,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [326, 156, 434, 243],
                "x": 377,
                "y": 247,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [546, 255, 656, 355],
                "x": 605,
                "y": 360,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [755, -89, 878, 0],
                "x": 821,
                "y": 2,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [666, 207, 794, 309],
                "x": 736,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [541, 245, 660, 337],
                "x": 595,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [151, 353, 275, 458],
                "x": 219,
                "y": 448,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [908, 679, 1031, 781],
                "x": 976,
                "y": 781,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [663, 133, 778, 242],
                "x": 720,
                "y": 241,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [602, 500, 722, 586],
                "x": 659,
                "y": 590,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [285, 110, 414, 229],
                "x": 355,
                "y": 219,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [539, 250, 660, 341],
                "x": 591,
                "y": 342,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [746, -108, 866, 3],
                "x": 815,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [703, 223, 831, 338],
                "x": 763,
                "y": 329,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [557, 222, 670, 336],
                "x": 617,
                "y": 327,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [132, 362, 259, 454],
                "x": 192,
                "y": 452,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [910, 677, 1037, 770],
                "x": 977,
                "y": 780,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [689, 114, 810, 210],
                "x": 745,
                "y": 216,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [620, 498, 744, 598],
                "x": 681,
                "y": 602,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [273, 85, 383, 188],
                "x": 333,
                "y": 193,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [511, 211, 645, 330],
                "x": 577,
                "y": 321,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [755, -98, 877, 2],
                "x": 809,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [736, 258, 845, 353],
                "x": 789,
                "y": 355,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [579, 210, 708, 310],
                "x": 638,
                "y": 315,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [94, 361, 230, 463],
                "x": 164,
                "y": 456,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [909, 685, 1042, 778],
                "x": 978,
                "y": 780,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [711, 98, 837, 194],
                "x": 769,
                "y": 188,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [650, 514, 770, 611],
                "x": 704,
                "y": 609,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [243, 63, 369, 173],
                "x": 311,
                "y": 169,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [506, 198, 624, 308],
                "x": 563,
                "y": 298,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 815, "y": 385, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [603, 204, 715, 300],
                "x": 659,
                "y": 303,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [76, 364, 193, 467],
                "x": 137,
                "y": 460,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [925, 675, 1041, 771],
                "x": 979,
                "y": 779,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [741, 60, 855, 167],
                "x": 794,
                "y": 157,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [675, 517, 796, 602],
                "x": 727,
                "y": 611,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [238, 55, 345, 148],
                "x": 288,
                "y": 147,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [496, 182, 607, 278],
                "x": 549,
                "y": 273,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [783, 318, 898, 415],
                "x": 842,
                "y": 420,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [630, 186, 732, 283],
                "x": 680,
                "y": 293,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [53, 355, 160, 461],
                "x": 109,
                "y": 464,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [920, 679, 1043, 784],
                "x": 981,
                "y": 779,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [752, 19, 871, 118],
                "x": 819,
                "y": 122,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [696, 512, 802, 604],
                "x": 750,
                "y": 607,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [215, 25, 330, 122],
                "x": 266,
                "y": 128,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [480, 137, 587, 250],
                "x": 535,
                "y": 246,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 868, "y": 459, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [651, 183, 760, 275],
                "x": 702,
                "y": 285,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [17, 369, 152, 465],
                "x": 82,
                "y": 468,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [931, 679, 1033, 786],
                "x": 982,
                "y": 778,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [779, -23, 901, 84],
                "x": 844,
                "y": 85,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [721, 498, 842, 594],
                "x": 772,
                "y": 596,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [179, 20, 307, 116],
                "x": 244,
                "y": 112,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [451, 120, 586, 221],
                "x": 521,
                "y": 217,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [832, 404, 948, 509],
                "x": 894,
                "y": 504,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 723, "y": 277, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [3, 376, 108, 477],
                "x": 54,
                "y": 472,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [926, 675, 1048, 769],
                "x": 983,
                "y": 778,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [819, -62, 931, 44],
                "x": 869,
                "y": 44,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [745, 486, 847, 574],
                "x": 795,
                "y": 579,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [153, 5, 281, 92],
                "x": 222,
                "y": 99,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 507, "y": 186, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [866, 461, 972, 549],
                "x": 921,
                "y": 553,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [688, 178, 794, 273],
                "x": 744,
                "y": 271,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-31, 385, 88, 467],
                "x": 27,
                "y": 476,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [928, 671, 1045, 777],
                "x": 984,
                "y": 778,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [843, -96, 955, 7],
                "x": 894,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [759, 457, 879, 564],
                "x": 818,
                "y": 554,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [137, -10, 262, 80],
                "x": 200,
                "y": 89,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [432, 47, 550, 153],
                "x": 493,
                "y": 153,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [889, 505, 1011, 616],
                "x": 947,
                "y": 608,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [713, 168, 830, 272],
                "x": 765,
                "y": 267,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-51, 373, 53, 476],
                "x": 0,
                "y": 482,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [921, 673, 1049, 768],
                "x": 985,
                "y": 777,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [770, 417, 901, 519],
                "x": 840,
                "y": 521,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [110, -26, 247, 85],
                "x": 177,
                "y": 84,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [422, 9, 547, 108],
                "x": 479,
                "y": 118,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [914, 572, 1033, 677],
                "x": 973,
                "y": 668,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [721, 164, 842, 267],
                "x": 787,
                "y": 265,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [931, 667, 1045, 782],
                "x": 986,
                "y": 777,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [803, 372, 926, 489],
                "x": 863,
                "y": 480,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [95, -13, 210, 81],
                "x": 155,
                "y": 82,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [402, -16, 525, 86],
                "x": 465,
                "y": 80,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [942, 632, 1070, 737],
                "x": 1000,
                "y": 733,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [745, 165, 872, 269],
                "x": 808,
                "y": 265,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [921, 680, 1048, 777],
                "x": 988,
                "y": 776,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [833, 328, 939, 437],
                "x": 886,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [67, -12, 202, 78],
                "x": 133,
                "y": 84,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [393, -67, 515, 42],
                "x": 451,
                "y": 41,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [762, 161, 894, 262],
                "x": 829,
                "y": 267,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [938, 676, 1042, 771],
                "x": 989,
                "y": 776,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [846, 268, 960, 371],
                "x": 909,
                "y": 371,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [44, -12, 175, 93],
                "x": 111,
                "y": 91,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [384, -94, 501, -9],
                "x": 437,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [799, 180, 903, 264],
                "x": 851,
                "y": 271,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [938, 680, 1055, 784],
                "x": 990,
                "y": 775,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [873, 202, 992, 292],
                "x": 931,
                "y": 301,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [33, -1, 155, 100],
                "x": 88,
                "y": 103,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [811, 173, 934, 274],
                "x": 872,
                "y": 278,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [931, 676, 1049, 778],
                "x": 991,
                "y": 775,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [896, 131, 1019, 230],
                "x": 954,
                "y": 221,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [12, 21, 124, 118],
                "x": 66,
                "y": 119,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [840, 182, 956, 277],
                "x": 893,
                "y": 287,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [927, 675, 1053, 784],
                "x": 992,
                "y": 775,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 977, "y": 131, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [-20, 44, 104, 143],
                "x": 44,
                "y": 141,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [861, 190, 978, 293],
                "x": 914,
                "y": 300,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [924, 684, 1047, 782],
                "x": 994,
                "y": 774,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [943, -61, 1056, 34],
                "x": 1000,
                "y": 29,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-47, 63, 82, 173],
                "x": 22,
                "y": 169,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [870, 212, 1004, 315],
                "x": 936,
                "y": 315,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [934, 682, 1055, 773],
                "x": 995,
                "y": 774,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-62, 99, 55, 198],
                "x": 0,
                "y": 203,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [890, 230, 1019, 338],
                "x": 957,
                "y": 333,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [926, 679, 1059, 783],
                "x": 996,
                "y": 773,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [920, 261, 1039, 363],
                "x": 978,
                "y": 354,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [937, 683, 1054, 763],
                "x": 997,
                "y": 773,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [933, 289, 1069, 373],
                "x": 1000,
                "y": 379,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 49,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 998, "y": 773, "track_id": None}
        ],
    },
    {
        "frame_id": 50,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [935, 663, 1058, 772],
                "x": 1000,
                "y": 772,
                "track_id": None,
            }
        ],
    },
]
