country_balls_amount = 5
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-52, 299, 52, 407],
                "x": 0,
                "y": 404,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-62, 193, 51, 298],
                "x": 0,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [36, 709, 156, 797],
                "x": 94,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [14, 704, 121, 790],
                "x": 70,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [933, 137, 1061, 234],
                "x": 1000,
                "y": 239,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-60, 288, 66, 388],
                "x": 4,
                "y": 386,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-53, 234, 72, 324],
                "x": 5,
                "y": 333,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [50, 635, 165, 735],
                "x": 114,
                "y": 744,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [36, 680, 154, 776],
                "x": 90,
                "y": 774,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [899, 155, 1031, 257],
                "x": 964,
                "y": 253,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-44, 268, 59, 359],
                "x": 9,
                "y": 369,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-43, 272, 68, 364],
                "x": 10,
                "y": 363,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [81, 588, 202, 694],
                "x": 134,
                "y": 693,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [56, 636, 164, 751],
                "x": 111,
                "y": 746,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [861, 170, 983, 259],
                "x": 928,
                "y": 263,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-54, 251, 77, 345],
                "x": 13,
                "y": 352,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-54, 283, 81, 387],
                "x": 16,
                "y": 393,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [99, 554, 210, 651],
                "x": 154,
                "y": 647,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [78, 613, 191, 724],
                "x": 132,
                "y": 716,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [824, 174, 956, 271],
                "x": 892,
                "y": 270,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-45, 229, 82, 326],
                "x": 18,
                "y": 335,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-39, 323, 86, 427],
                "x": 21,
                "y": 421,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [108, 507, 238, 615],
                "x": 174,
                "y": 605,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [94, 583, 215, 674],
                "x": 153,
                "y": 684,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [795, 176, 925, 264],
                "x": 857,
                "y": 274,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-44, 226, 88, 327],
                "x": 22,
                "y": 320,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-36, 351, 91, 442],
                "x": 26,
                "y": 449,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [135, 466, 262, 573],
                "x": 194,
                "y": 568,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [108, 552, 235, 647],
                "x": 174,
                "y": 651,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [760, 170, 884, 270],
                "x": 821,
                "y": 276,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-28, 205, 95, 307],
                "x": 27,
                "y": 304,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-18, 381, 95, 481],
                "x": 32,
                "y": 476,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [146, 436, 270, 539],
                "x": 214,
                "y": 534,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [132, 517, 257, 613],
                "x": 195,
                "y": 617,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [724, 168, 842, 286],
                "x": 785,
                "y": 276,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-22, 196, 82, 289],
                "x": 31,
                "y": 289,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-26, 404, 96, 493],
                "x": 37,
                "y": 502,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [169, 406, 301, 506],
                "x": 234,
                "y": 504,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [165, 480, 269, 587],
                "x": 215,
                "y": 582,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [685, 183, 812, 279],
                "x": 750,
                "y": 276,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-33, 173, 103, 277],
                "x": 36,
                "y": 274,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-11, 421, 93, 518],
                "x": 42,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [201, 374, 323, 475],
                "x": 255,
                "y": 478,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [170, 453, 305, 542],
                "x": 236,
                "y": 547,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [648, 164, 768, 267],
                "x": 714,
                "y": 274,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-21, 162, 95, 253],
                "x": 40,
                "y": 260,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-2, 444, 108, 557],
                "x": 48,
                "y": 552,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [225, 362, 342, 465],
                "x": 275,
                "y": 455,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [193, 414, 311, 505],
                "x": 257,
                "y": 512,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [617, 182, 738, 264],
                "x": 678,
                "y": 272,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-13, 140, 106, 238],
                "x": 45,
                "y": 246,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-12, 467, 114, 585],
                "x": 53,
                "y": 576,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [234, 343, 360, 434],
                "x": 295,
                "y": 436,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [219, 371, 339, 468],
                "x": 278,
                "y": 477,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [586, 177, 705, 262],
                "x": 642,
                "y": 270,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-7, 138, 107, 224],
                "x": 50,
                "y": 233,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [6, 493, 112, 597],
                "x": 59,
                "y": 598,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [246, 318, 368, 421],
                "x": 315,
                "y": 419,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [237, 334, 352, 440],
                "x": 299,
                "y": 443,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [556, 169, 674, 268],
                "x": 607,
                "y": 269,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-11, 112, 104, 224],
                "x": 54,
                "y": 220,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [3, 527, 120, 611],
                "x": 64,
                "y": 620,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [265, 299, 388, 400],
                "x": 335,
                "y": 406,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [263, 306, 382, 404],
                "x": 320,
                "y": 410,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [515, 172, 629, 260],
                "x": 571,
                "y": 269,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [6, 109, 119, 206],
                "x": 59,
                "y": 207,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [16, 552, 132, 638],
                "x": 69,
                "y": 642,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [305, 305, 422, 400],
                "x": 355,
                "y": 395,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [272, 268, 409, 383],
                "x": 340,
                "y": 378,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [472, 166, 598, 279],
                "x": 535,
                "y": 269,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-2, 88, 127, 194],
                "x": 63,
                "y": 195,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [14, 554, 140, 664],
                "x": 75,
                "y": 662,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [306, 284, 438, 392],
                "x": 375,
                "y": 386,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [291, 243, 418, 356],
                "x": 361,
                "y": 348,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [450, 162, 556, 267],
                "x": 500,
                "y": 272,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [5, 79, 135, 181],
                "x": 68,
                "y": 183,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [25, 584, 148, 676],
                "x": 80,
                "y": 682,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [345, 275, 458, 374],
                "x": 396,
                "y": 380,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [317, 216, 443, 320],
                "x": 382,
                "y": 320,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [411, 182, 528, 286],
                "x": 464,
                "y": 277,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [14, 76, 128, 174],
                "x": 72,
                "y": 171,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [21, 609, 149, 698],
                "x": 85,
                "y": 701,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [346, 265, 476, 383],
                "x": 416,
                "y": 375,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [338, 202, 463, 299],
                "x": 403,
                "y": 295,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [374, 188, 490, 295],
                "x": 428,
                "y": 285,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [10, 69, 143, 151],
                "x": 77,
                "y": 160,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [35, 615, 144, 726],
                "x": 91,
                "y": 719,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [374, 273, 494, 380],
                "x": 436,
                "y": 373,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [356, 169, 480, 265],
                "x": 424,
                "y": 272,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [335, 194, 457, 289],
                "x": 392,
                "y": 296,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [17, 46, 133, 154],
                "x": 81,
                "y": 150,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [28, 637, 165, 743],
                "x": 96,
                "y": 737,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [391, 279, 522, 373],
                "x": 456,
                "y": 372,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [376, 162, 512, 257],
                "x": 445,
                "y": 252,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [292, 200, 420, 308],
                "x": 357,
                "y": 310,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [23, 45, 155, 139],
                "x": 86,
                "y": 139,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [45, 656, 156, 750],
                "x": 101,
                "y": 753,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [424, 281, 541, 371],
                "x": 476,
                "y": 373,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [402, 134, 519, 242],
                "x": 465,
                "y": 235,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [270, 231, 374, 337],
                "x": 321,
                "y": 329,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [29, 38, 160, 136],
                "x": 90,
                "y": 130,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [49, 664, 169, 760],
                "x": 107,
                "y": 769,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [438, 268, 553, 379],
                "x": 496,
                "y": 375,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [422, 112, 546, 214],
                "x": 486,
                "y": 222,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [220, 257, 350, 356],
                "x": 285,
                "y": 352,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [27, 21, 165, 113],
                "x": 95,
                "y": 120,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [46, 677, 163, 784],
                "x": 112,
                "y": 785,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [446, 286, 570, 387],
                "x": 516,
                "y": 378,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [454, 108, 573, 221],
                "x": 507,
                "y": 214,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [185, 285, 309, 378],
                "x": 250,
                "y": 379,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [35, 17, 163, 112],
                "x": 100,
                "y": 111,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [64, 709, 174, 803],
                "x": 118,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [485, 281, 586, 376],
                "x": 536,
                "y": 382,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [474, 100, 592, 213],
                "x": 528,
                "y": 209,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [163, 307, 272, 403],
                "x": 214,
                "y": 412,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [54, 0, 159, 94],
                "x": 104,
                "y": 102,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [497, 279, 627, 380],
                "x": 557,
                "y": 387,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [495, 118, 603, 212],
                "x": 549,
                "y": 210,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [123, 346, 232, 450],
                "x": 178,
                "y": 451,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [57, -11, 167, 89],
                "x": 109,
                "y": 94,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [511, 282, 644, 390],
                "x": 577,
                "y": 392,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [502, 106, 630, 215],
                "x": 570,
                "y": 215,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [78, 389, 198, 487],
                "x": 142,
                "y": 496,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [56, -13, 171, 85],
                "x": 113,
                "y": 86,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [535, 300, 659, 397],
                "x": 597,
                "y": 398,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [534, 136, 660, 227],
                "x": 590,
                "y": 226,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [46, 447, 177, 558],
                "x": 107,
                "y": 548,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [50, -32, 183, 85],
                "x": 118,
                "y": 78,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [552, 295, 667, 403],
                "x": 617,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [554, 141, 671, 250],
                "x": 611,
                "y": 243,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [1, 501, 130, 615],
                "x": 71,
                "y": 607,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [68, -23, 177, 65],
                "x": 122,
                "y": 71,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [571, 314, 690, 417],
                "x": 637,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [577, 163, 690, 256],
                "x": 632,
                "y": 265,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-23, 568, 87, 675],
                "x": 35,
                "y": 673,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [59, -44, 196, 55],
                "x": 127,
                "y": 64,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [588, 310, 721, 423],
                "x": 657,
                "y": 415,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [586, 191, 723, 304],
                "x": 653,
                "y": 294,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-61, 652, 66, 750],
                "x": 0,
                "y": 748,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [80, -44, 184, 61],
                "x": 131,
                "y": 57,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [621, 318, 743, 413],
                "x": 677,
                "y": 419,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [604, 233, 743, 334],
                "x": 674,
                "y": 330,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [83, -53, 187, 55],
                "x": 136,
                "y": 51,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [633, 314, 765, 424],
                "x": 698,
                "y": 424,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [631, 277, 756, 383],
                "x": 695,
                "y": 373,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [76, -56, 204, 54],
                "x": 140,
                "y": 45,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [667, 325, 781, 436],
                "x": 718,
                "y": 427,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [661, 316, 777, 427],
                "x": 715,
                "y": 424,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [93, -63, 198, 39],
                "x": 145,
                "y": 40,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [668, 332, 807, 433],
                "x": 738,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [674, 377, 802, 472],
                "x": 736,
                "y": 482,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [91, -65, 214, 26],
                "x": 150,
                "y": 34,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [693, 338, 811, 422],
                "x": 758,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [706, 446, 817, 555],
                "x": 757,
                "y": 548,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [102, -78, 218, 34],
                "x": 154,
                "y": 30,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [723, 323, 840, 440],
                "x": 778,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [726, 514, 845, 618],
                "x": 778,
                "y": 623,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [97, -66, 222, 22],
                "x": 159,
                "y": 25,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [735, 325, 866, 435],
                "x": 798,
                "y": 429,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [733, 613, 866, 713],
                "x": 799,
                "y": 707,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [108, -85, 219, 23],
                "x": 163,
                "y": 21,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [750, 333, 875, 431],
                "x": 818,
                "y": 425,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [770, 703, 875, 794],
                "x": 820,
                "y": 799,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [112, -84, 223, 25],
                "x": 168,
                "y": 17,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [783, 312, 894, 429],
                "x": 838,
                "y": 420,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [102, -76, 235, 22],
                "x": 172,
                "y": 14,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [790, 306, 920, 405],
                "x": 859,
                "y": 412,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [126, -81, 234, 15],
                "x": 177,
                "y": 10,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [826, 309, 937, 395],
                "x": 879,
                "y": 402,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [115, -99, 238, 3],
                "x": 181,
                "y": 8,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [842, 286, 954, 379],
                "x": 899,
                "y": 389,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [118, -87, 238, -2],
                "x": 186,
                "y": 5,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [865, 270, 982, 381],
                "x": 919,
                "y": 374,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [133, -101, 259, 6],
                "x": 190,
                "y": 3,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [885, 256, 992, 351],
                "x": 939,
                "y": 355,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [142, -99, 263, -2],
                "x": 195,
                "y": 1,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [902, 236, 1027, 328],
                "x": 959,
                "y": 334,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [144, -90, 259, 4],
                "x": 200,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [909, 212, 1038, 319],
                "x": 979,
                "y": 309,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 2,
                "bounding_box": [945, 178, 1057, 274],
                "x": 1000,
                "y": 281,
                "track_id": None,
            }
        ],
    },
]
