country_balls_amount = 5
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [940, 46, 1060, 146],
                "x": 1000,
                "y": 146,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [940, -17, 1060, 83],
                "x": 1000,
                "y": 83,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [940, 548, 1060, 648],
                "x": 1000,
                "y": 648,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [842, -100, 962, 0],
                "x": 902,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [940, 472, 1060, 572],
                "x": 1000,
                "y": 572,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [919, 86, 1039, 186],
                "x": 979,
                "y": 186,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [900, 21, 1020, 121],
                "x": 960,
                "y": 121,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [898, 585, 1018, 685],
                "x": 958,
                "y": 685,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [845, -87, 965, 13],
                "x": 905,
                "y": 13,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [901, 290, 1021, 390],
                "x": 961,
                "y": 390,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [898, 125, 1018, 225],
                "x": 958,
                "y": 225,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [860, 55, 980, 155],
                "x": 920,
                "y": 155,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [856, 605, 976, 705],
                "x": 916,
                "y": 705,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [848, -74, 968, 26],
                "x": 908,
                "y": 26,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [862, 150, 982, 250],
                "x": 922,
                "y": 250,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [877, 161, 997, 261],
                "x": 937,
                "y": 261,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [820, 84, 940, 184],
                "x": 880,
                "y": 184,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [815, 610, 935, 710],
                "x": 875,
                "y": 710,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [851, -60, 971, 40],
                "x": 911,
                "y": 40,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [823, 49, 943, 149],
                "x": 883,
                "y": 149,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [856, 196, 976, 296],
                "x": 916,
                "y": 296,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [780, 109, 900, 209],
                "x": 840,
                "y": 209,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [773, 601, 893, 701],
                "x": 833,
                "y": 701,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [854, -45, 974, 55],
                "x": 914,
                "y": 55,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [784, -17, 904, 83],
                "x": 844,
                "y": 83,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [835, 228, 955, 328],
                "x": 895,
                "y": 328,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [740, 130, 860, 230],
                "x": 800,
                "y": 230,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [731, 581, 851, 681],
                "x": 791,
                "y": 681,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [857, -30, 977, 70],
                "x": 917,
                "y": 70,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [745, -53, 865, 47],
                "x": 805,
                "y": 47,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [815, 259, 935, 359],
                "x": 875,
                "y": 359,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [700, 147, 820, 247],
                "x": 760,
                "y": 247,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [690, 551, 810, 651],
                "x": 750,
                "y": 651,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [860, -14, 980, 86],
                "x": 920,
                "y": 86,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [706, -62, 826, 38],
                "x": 766,
                "y": 38,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [794, 288, 914, 388],
                "x": 854,
                "y": 388,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [660, 160, 780, 260],
                "x": 720,
                "y": 260,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [648, 512, 768, 612],
                "x": 708,
                "y": 612,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [864, 2, 984, 102],
                "x": 924,
                "y": 102,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [667, -48, 787, 52],
                "x": 727,
                "y": 52,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [773, 315, 893, 415],
                "x": 833,
                "y": 415,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [620, 170, 740, 270],
                "x": 680,
                "y": 270,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [606, 468, 726, 568],
                "x": 666,
                "y": 568,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [867, 18, 987, 118],
                "x": 927,
                "y": 118,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [628, -14, 748, 86],
                "x": 688,
                "y": 86,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [752, 339, 872, 439],
                "x": 812,
                "y": 439,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [580, 178, 700, 278],
                "x": 640,
                "y": 278,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [565, 420, 685, 520],
                "x": 625,
                "y": 520,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [870, 35, 990, 135],
                "x": 930,
                "y": 135,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [589, 34, 709, 134],
                "x": 649,
                "y": 134,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [731, 362, 851, 462],
                "x": 791,
                "y": 462,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [540, 182, 660, 282],
                "x": 600,
                "y": 282,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [523, 369, 643, 469],
                "x": 583,
                "y": 469,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [873, 53, 993, 153],
                "x": 933,
                "y": 153,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [550, 93, 670, 193],
                "x": 610,
                "y": 193,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [710, 383, 830, 483],
                "x": 770,
                "y": 483,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [500, 185, 620, 285],
                "x": 560,
                "y": 285,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [481, 317, 601, 417],
                "x": 541,
                "y": 417,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [876, 71, 996, 171],
                "x": 936,
                "y": 171,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [511, 160, 631, 260],
                "x": 571,
                "y": 260,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [690, 401, 810, 501],
                "x": 750,
                "y": 501,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [460, 185, 580, 285],
                "x": 520,
                "y": 285,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [440, 267, 560, 367],
                "x": 500,
                "y": 367,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [879, 90, 999, 190],
                "x": 939,
                "y": 190,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [473, 230, 593, 330],
                "x": 533,
                "y": 330,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [669, 417, 789, 517],
                "x": 729,
                "y": 517,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [420, 183, 540, 283],
                "x": 480,
                "y": 283,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [398, 221, 518, 321],
                "x": 458,
                "y": 321,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [883, 109, 1003, 209],
                "x": 943,
                "y": 209,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [434, 300, 554, 400],
                "x": 494,
                "y": 400,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [648, 431, 768, 531],
                "x": 708,
                "y": 531,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [380, 180, 500, 280],
                "x": 440,
                "y": 280,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [356, 179, 476, 279],
                "x": 416,
                "y": 279,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [886, 129, 1006, 229],
                "x": 946,
                "y": 229,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [395, 364, 515, 464],
                "x": 455,
                "y": 464,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [627, 442, 747, 542],
                "x": 687,
                "y": 542,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [340, 175, 460, 275],
                "x": 400,
                "y": 275,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [315, 144, 435, 244],
                "x": 375,
                "y": 244,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [889, 149, 1009, 249],
                "x": 949,
                "y": 249,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [356, 421, 476, 521],
                "x": 416,
                "y": 521,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [606, 451, 726, 551],
                "x": 666,
                "y": 551,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [300, 169, 420, 269],
                "x": 360,
                "y": 269,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [273, 118, 393, 218],
                "x": 333,
                "y": 218,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [892, 170, 1012, 270],
                "x": 952,
                "y": 270,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [317, 465, 437, 565],
                "x": 377,
                "y": 565,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [586, 458, 706, 558],
                "x": 646,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [260, 162, 380, 262],
                "x": 320,
                "y": 262,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [231, 103, 351, 203],
                "x": 291,
                "y": 203,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [895, 191, 1015, 291],
                "x": 955,
                "y": 291,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [278, 493, 398, 593],
                "x": 338,
                "y": 593,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [565, 462, 685, 562],
                "x": 625,
                "y": 562,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [220, 155, 340, 255],
                "x": 280,
                "y": 255,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [190, 101, 310, 201],
                "x": 250,
                "y": 201,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [898, 213, 1018, 313],
                "x": 958,
                "y": 313,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [239, 500, 359, 600],
                "x": 299,
                "y": 600,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [544, 464, 664, 564],
                "x": 604,
                "y": 564,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [180, 148, 300, 248],
                "x": 240,
                "y": 248,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [148, 112, 268, 212],
                "x": 208,
                "y": 212,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [902, 236, 1022, 336],
                "x": 962,
                "y": 336,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [200, 483, 320, 583],
                "x": 260,
                "y": 583,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [523, 463, 643, 563],
                "x": 583,
                "y": 563,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [140, 141, 260, 241],
                "x": 200,
                "y": 241,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [106, 140, 226, 240],
                "x": 166,
                "y": 240,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [905, 259, 1025, 359],
                "x": 965,
                "y": 359,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [161, 438, 281, 538],
                "x": 221,
                "y": 538,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [502, 459, 622, 559],
                "x": 562,
                "y": 559,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [100, 134, 220, 234],
                "x": 160,
                "y": 234,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [65, 186, 185, 286],
                "x": 125,
                "y": 286,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [908, 283, 1028, 383],
                "x": 968,
                "y": 383,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [122, 362, 242, 462],
                "x": 182,
                "y": 462,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [481, 453, 601, 553],
                "x": 541,
                "y": 553,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [60, 127, 180, 227],
                "x": 120,
                "y": 227,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [23, 253, 143, 353],
                "x": 83,
                "y": 353,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [911, 307, 1031, 407],
                "x": 971,
                "y": 407,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [83, 249, 203, 349],
                "x": 143,
                "y": 349,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [461, 444, 581, 544],
                "x": 521,
                "y": 544,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [20, 122, 140, 222],
                "x": 80,
                "y": 222,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-19, 341, 101, 441],
                "x": 41,
                "y": 441,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [914, 332, 1034, 432],
                "x": 974,
                "y": 432,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [44, 96, 164, 196],
                "x": 104,
                "y": 196,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [440, 433, 560, 533],
                "x": 500,
                "y": 533,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-20, 118, 100, 218],
                "x": 40,
                "y": 218,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [-60, 453, 60, 553],
                "x": 0,
                "y": 553,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [917, 357, 1037, 457],
                "x": 977,
                "y": 457,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [6, -100, 126, 0],
                "x": 66,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [419, 418, 539, 518],
                "x": 479,
                "y": 518,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-60, 115, 60, 215],
                "x": 0,
                "y": 215,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [921, 383, 1041, 483],
                "x": 981,
                "y": 483,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [398, 401, 518, 501],
                "x": 458,
                "y": 501,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [924, 410, 1044, 510],
                "x": 984,
                "y": 510,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [377, 381, 497, 481],
                "x": 437,
                "y": 481,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [927, 437, 1047, 537],
                "x": 987,
                "y": 537,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [357, 358, 477, 458],
                "x": 417,
                "y": 458,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [930, 465, 1050, 565],
                "x": 990,
                "y": 565,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [336, 332, 456, 432],
                "x": 396,
                "y": 432,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [933, 494, 1053, 594],
                "x": 993,
                "y": 594,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [315, 303, 435, 403],
                "x": 375,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [936, 523, 1056, 623],
                "x": 996,
                "y": 623,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [294, 271, 414, 371],
                "x": 354,
                "y": 371,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [940, 553, 1060, 653],
                "x": 1000,
                "y": 653,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [273, 236, 393, 336],
                "x": 333,
                "y": 336,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [252, 198, 372, 298],
                "x": 312,
                "y": 298,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [232, 156, 352, 256],
                "x": 292,
                "y": 256,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [211, 112, 331, 212],
                "x": 271,
                "y": 212,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [190, 64, 310, 164],
                "x": 250,
                "y": 164,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [169, 12, 289, 112],
                "x": 229,
                "y": 112,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [148, -42, 268, 58],
                "x": 208,
                "y": 58,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [128, -100, 248, 0],
                "x": 188,
                "y": 0,
                "track_id": None,
            }
        ],
    },
]
